version: '3.9'

services:
  redis:
    image: 'redis'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
  dumbbot:
    depends_on:
      - redis
    restart: unless-stopped
    build: .
