name: Build and Deploy

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: cd into repo
        uses: actions/checkout@v3
      - name: Install linux dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev ffmpeg libtool make autoconf automake g++ python3 rsync
      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          # TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
